アイコンテキストボタンに背景画像をつけられるように修正
HiroMoriguchi-pioneer/FigmaToCode pull request #59
Opened 2024-05-09 06:14 UTC by tharada-s

## Done
- アイコンテキストボタンに背景画像をつけられるように修正 0c9c1edff988d163b64d7c9f58fe205a975fcfeb

2024-05-09 07:20 UTC, HiroMoriguchi-pioneer requested changes

2024-05-09 07:20 UTC, HiroMoriguchi-pioneer commented on packages/backend/src/android/builderImpl/androidButtonType.ts
> +    && androidNameParser(child.name).type !== AndroidType.linearLayout
元のコードからそうなんやけど、条件が増えて一段と読みにくくなったんで、論理式の階層に合わせて字下げとかしてもらえませんか？

2024-05-10 05:27 UTC, tharada-s commented on packages/backend/src/android/builderImpl/androidButtonType.ts
> +    && androidNameParser(child.name).type !== AndroidType.linearLayout
修正しました。

2024-05-13 00:17 UTC, HiroMoriguchi-pioneer approved these changes

2024-05-13 00:21 UTC, merged